# -*- coding: utf-8 -*-
"""_index.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/_index.ipynb

##### Copyright 2018 The TensorFlow Authors.

Licensed under the Apache License, Version 2.0 (the "License");
"""

#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""# Get Started with TensorFlow

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/_index.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/_index.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
</table>

This is a [Google Colaboratory](https://colab.research.google.com/notebooks/welcome.ipynb) notebook file. Python programs are run directly in the browser—a great way to learn and use TensorFlow. To run the Colab notebook:

1. Connect to a Python runtime: At the top-right of the menu bar, select *CONNECT*.
2. Run all the notebook code cells: Select *Runtime* > *Run all*.

For more examples and guides (including details for this program), see [Get Started with TensorFlow](https://www.tensorflow.org/get_started/).

Let's get started, import the TensorFlow library into your program:

Load and prepare the [MNIST](http://yann.lecun.com/exdb/mnist/) dataset. Convert the samples from integers to floating-point numbers:
"""

import matplotlib.pyplot as plt
mnist = tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test) = mnist.load_data() # loads the data from mnist Dataset to x_train,y_train and x_test,y_test
x_train = tf.keras.utils.normalize(x_train,axis=1)
x_test = tf.keras.utils.normalize(x_test,axis=1)
#print(x_train[1100])

model = tf.keras.models.Sequential()   #model creation starts here
model.add = tf.keras.layers.Flatten(input_shape=(28,28))
model.add = tf.keras.layers.Dense(128,activation=tf.nn.relu)
model.add = tf.keras.layers.Dense(128,activation=tf.nn.relu)
model.add = tf.keras.layers.Dense(10,activation=tf.nn.softmax) # the o/p neuron size is 10 coz o/p will be either of the 10 digits

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy']) #compiling the model with given params

model.fit(x_train,y_train,epochs=1) # running the model

val_loss,val_acc = model.evaluate(x_test,y_test) #Evaluate model 

print(val_loss*100,val_acc*100)

model.save('numreader.model') # save the model

newmod = tf.keras.models.load_model('numreader.model') # using the model to predict output

predicts = newmod.predict(x_test)

import numpy as np
print(np.argmax(predicts[154])) # Tested for img with index 154(selected 154 arbitrarily!)
plt.imshow(x_test[154],cmap='binary') # just to check if the img with 154 index is matching with prediction
plt.show()